project_id = "bjuxpqtsfnkaonczauxz"

[functions.manage-users]
verify_jwt = false

[functions.simulation-insights]
verify_jwt = false

[functions.hr-bulk-import]
verify_jwt = false

[functions.feedz-sync]
verify_jwt = false
