project_id = "bjuxpqtsfnkaonczauxz"

[functions.manage-users]
verify_jwt = false

[functions.simulation-insights]
verify_jwt = false

[functions.hr-bulk-import]
verify_jwt = false

[functions.feedz-sync]
verify_jwt = false

[functions.feedz-rollback]
verify_jwt = false

[functions.hr-apply-corrections]
verify_jwt = false

[functions.hr-rollback-corrections]
verify_jwt = false

[functions.feedz-update-termination-dates]
verify_jwt = false

[functions.hr-update-matriculas]
verify_jwt = false
