ALTER TYPE public.module_key ADD VALUE IF NOT EXISTS 'OVERTIME';
ALTER TYPE public.module_key ADD VALUE IF NOT EXISTS 'TRANSPORT';
ALTER TYPE public.module_key ADD VALUE IF NOT EXISTS 'JOB_REQUESTS';
ALTER TYPE public.module_key ADD VALUE IF NOT EXISTS 'JOB_SKILLS';